// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAEbk0g2WKzaJOP56vMP5bnpWvK2DuBprk',
    appId: '1:48179351087:web:d0ac5913116c26140900da',
    messagingSenderId: '48179351087',
    projectId: 'agronova-d94b1',
    authDomain: 'agronova-d94b1.firebaseapp.com',
    databaseURL: 'https://agronova-d94b1-default-rtdb.firebaseio.com',
    storageBucket: 'agronova-d94b1.firebasestorage.app',
    measurementId: 'G-JCSGRGPEB6',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB3EkPLNC92lcMtOVTKatnRgLMJoCDdwCA',
    appId: '1:48179351087:android:509fa31d1fdcd8f80900da',
    messagingSenderId: '48179351087',
    projectId: 'agronova-d94b1',
    databaseURL: 'https://agronova-d94b1-default-rtdb.firebaseio.com',
    storageBucket: 'agronova-d94b1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyChKVtivRidIv08f4vaix5VbqNl6FeMCqY',
    appId: '1:48179351087:ios:edf591e44c4398d60900da',
    messagingSenderId: '48179351087',
    projectId: 'agronova-d94b1',
    databaseURL: 'https://agronova-d94b1-default-rtdb.firebaseio.com',
    storageBucket: 'agronova-d94b1.firebasestorage.app',
    iosBundleId: 'com.example.pracApp',
  );
}
